### ISSUE TITLE
Help Needed with "SurvTMLE" code.

### ISSUE THREAD

**Issue by Roya-Riahi** [detal9/SurvTMLE#1]
Dear Professor Talbot,
I have a question regarding the running of the helpful "SurvTMLE" code, and I would greatly appreciate your guidance in this matter.

I have a dataset containing U1, U2, U3, U4, U5 (as time-fixed baseline covariates), X (as binary exposure), time, and event. Considering the time points vector as times = c(0.16,0.40,0.95), I ran the following code:

for (j in 1:length(times)) {
  Mysample [paste0("y", j)] <- as.numeric(Mysample$time <= times[j])
  Mysample [paste0("Censor", j)] <- as.numeric(Mysample$time <= times[j])
}
Fits= surv.TMLE(dat = Mysample, Yvar = c("y1", "y2", "y3"), Cvar = c("Censor1", "Censor2","Censor3"), Avar="X", Lvar= list(c("U1","U2","U3","U4","U5"),c("U1","U2","U3", "U4","U5"),c("U1","U2","U3", "U4","U5")), L0var = NULL, lookback = 1,Ymod = "parametric", Cmod = "parametric", Amod = "parametric", gbound = 0.005, V = 5, MSM.form = ~X+as.factor(time), Print = FALSE);

But, the obtained output was as follows, in which all estimated survival probabilities were equal to one! :

$St
  S.0 S.1       SE.S.0       SE.S.1
1   1   1 0.000000e+00 0.000000e+00
2   1   1 1.838894e-13 2.235057e-13
3   1   1 2.751393e-13 3.561504e-13
4   1   1 3.140446e-13 4.393580e-13

$MSM
                                  Coef                  SE                lower95       upper95
(Intercept)          -24.514218597 0.00631536 -24.52659649 -24.50184070
X                         -0.004796799 0.009033330  -0.02250180   0.012908202
as.factor(time)2  -0.024306584 0.005852834  -0.03577793  -0.012835240
as.factor(time)3  -0.024669436 0.011244267  -0.04670780  -0.002631077

$vcov
                              (Intercept)             X                as.factor(time)2   as.factor(time)3
(Intercept)           3.988389e-05 -3.328424e-05    -1.513636e-05    -4.561812e-05
X                        -3.328424e-05  8.160105e-05    -5.146703e-06     1.521291e-05
as.factor(time)2 -1.513636e-05 -5.146703e-06     3.425567e-05     2.259401e-05
as.factor(time)3 -4.561812e-05  1.521291e-05     2.259401e-05     1.264335e-04

Thank you very much in advance for your consideration.

**Comment by detal9** [comment]
Dear RoYa,

I think the issue is that all observations are marked both as censored and as having an event when the follow-up time is lower than the time of interest by the following code:

for (j in 1:length(times)) {
Mysample [paste0("y", j)] <- as.numeric(Mysample$time <= times[j])
Mysample [paste0("Censor", j)] <- as.numeric(Mysample$time <= times[j])
}

If you have an event indicator (say "event"), then the code could be modified to be:

for (j in 1:length(times)) {
Mysample [paste0("y", j)] <- as.numeric(Mysample$time <= times[j])*event
Mysample [paste0("Censor", j)] <- as.numeric(Mysample$time <= times[j])*(1 - event)
}

That way, it would be clarified if the follow-up ended because of an event or because of a censoring (e.g., loss to follow-up).

Please let me know if that solves the issue.

Best wishes,

Denis

**Comment by Roya-Riahi** [comment]
Dear professor Talbot,

Thank you very much for your guidance.

Sorry that I made a mistake in my coding. I corrected the code according to your suggestion, and the issue was solved. I was able to get the correct output.


I appreciate your kindness.
